### ISSUE TITLE
解压后无ToastFish.exe？ 

### ISSUE THREAD

**Issue by montau59** [Uahh/ToastFish#10]
解压后没有出现exe文件，请问是什么问题？
![missing](https://user-images.githubusercontent.com/34331579/120605630-deef1300-c480-11eb-8e1b-b032d1c8eb49.jpg)

**Comment by Uahh** [comment]
这个是源码，exe需要去网盘下载
百度网盘： https://pan.baidu.com/s/1X9eImdqUIY--I5z9vUkUVA 提取码：2173

**Comment by montau59** [comment]
> 这个是源码，exe需要去网盘下载
> 百度网盘： https://pan.baidu.com/s/1X9eImdqUIY--I5z9vUkUVA 提取码：2173

终于成功使用啦~想法真的很赞！感谢！
