### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by sang640** [Uahh/ToastFish#13]
你好，请问方便加个日语系列吗

**Comment by Uahh** [comment]
没有词库..如果我找到词库就加！

**Comment by sang640** [comment]
好的！！辛苦啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月7日(星期一) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Uahh/ToastFish] ISSUE (#13)





 
没有词库..如果我找到词库就加！
 
&mdash;
