### ISSUE TITLE
2020年6月7日

### ISSUE THREAD

**Issue by Timmerre** [Uahh/ToastFish#15]
1、建议点击发音后，界面不要闪现
2、建议设置单词个数能自定义
3、建议学习情况的简单的统计

**Comment by Uahh** [comment]
1. 由于通知接口的限制，这个没办法解决
2. 这个可以，下版本加
3. 会认真考虑怎么做

**Comment by Timmerre** [comment]
1、单词看中文选英语，选项的正确答案85%都在b选项，建议增加随机性；
2、单词看中文选英语，建议选择正确时就不用弹窗出现，选择错误出现该选项的正确答应；
3、建议能使用键盘的左右键，经常点鼠标手疼。

**Comment by Uahh** [comment]
1. 我测没这个问题呀..是不是运气不太好
2. 啊..考虑了下还是弹，不然没个反馈奇怪有点奇怪。
3. 通知按钮不能直接设置快捷键55555555
