### ISSUE TITLE
22H2安装后打不开应用，会直接闪退

### ISSUE THREAD

**Issue by linzepore** [Uahh/ToastFish#156]
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎1/‎3
操作系统版本	22621.2134
体验	Windows Feature Experience Pack 1000.22659.1000.0

https://github.com/Uahh/ToastFish/assets/51522645/0c301f18-2f20-4cf7-b563-c76b1055965c

**Comment by fenda1-1** [comment]
一样闪退

**Comment by fenda1-1** [comment]
你可以试试下载源码，把应用转成uwp，应该可以解决

**Comment by fenda1-1** [comment]
你打开源代码，加一条显示的回调函数试试

**Comment by KisroO** [comment]
我的是Windows 11 家庭中文版，问题也是和你一样的，msi和zip都试过了，还是无法正常运行.

**Comment by linzepore** [comment]
我的是专业版，在偶然的更新后已经可以了
