### ISSUE TITLE
音标重音显示有误

### ISSUE THREAD

**Issue by yummyspringroll** [Uahh/ToastFish#16]
![无标题](https://user-images.githubusercontent.com/53401010/121449316-2539fa00-c9cc-11eb-96b7-f447487cef2f.png)
有些单词的音标会显示两个以上的重音
感谢您开发的软件

**Comment by Uahh** [comment]
词库是新东方的，有疑问的音标经过验证，在英汉词典上都是有标注的，不用担心是错误的。
