### ISSUE TITLE
按键

### ISSUE THREAD

**Issue by yfy200113** [Uahh/ToastFish#24]
或许可以有按键控制嘛

**Comment by Uahh** [comment]
通知栏的按钮不能直接添加快捷键，但或许可以通过别的方法间接添加，我还正在研究。(点个Star呀🥲)

**Comment by yfy200113** [comment]
嗷嗷好的，辛苦啦，已经很厉害了！（刚刚点了）

**Comment by Uahh** [comment]
谢谢^_^> 嗷嗷好的，辛苦啦，已经很厉害了！（刚刚点了）
