### ISSUE TITLE
可以考虑添加一些更完善的日语单词

### ISSUE THREAD

**Issue by sinsiuwo** [Uahh/ToastFish#25]
希望能有支持考级对应的单词表

**Comment by Uahh** [comment]
我没有找到更多的词库，如果您有词库资源可以联系我，资源可以是任何可读形式，excel/Json/db都可以。
每个词至少需要包含词性，词义和单词本身。

**Comment by Uahh** [comment]
> 希望能有支持考级对应的单词表

我没有找到更多的词库，如果您有词库资源可以联系我，资源可以是任何可读形式，excel/Json/db都可以。
每个词至少需要包含词性，词义和单词本身。

**Comment by sinsiuwo** [comment]
在 2021-08-02 16:29:53，"Uahh" ***@***.***> 写道：

希望能有支持考级对应的单词表

我没有找到更多的词库，如果您有词库资源可以联系我，资源可以是任何可读形式，excel/Json/db都可以。
每个词至少需要包含词性，词义和单词本身。
