### ISSUE TITLE
widnows 7 启动异常

### ISSUE THREAD

**Issue by luchatex** [Uahh/ToastFish#26]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	ToastFish.exe
  问题签名 02:	1.0.0.0
  问题签名 03:	d7f8a3c0
  问题签名 04:	PresentationFramework
  问题签名 05:	4.8.3928.0
  问题签名 06:	5d3907bb
  问题签名 07:	2261
  问题签名 08:	f6
  问题签名 09:	System.Windows.Markup.XamlParse
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by luchatex** [comment]
不支持win7的话，希望增加支持。

**Comment by Uahh** [comment]
> 不支持win7的话，希望增加支持。

win7没有通知栏这个模块, 以后可能会单独写个软件来支持。

**Comment by JohyC** [comment]
> 问题签名:
> 问题事件名称: CLR20r3
> 问题签名 01: ToastFish.exe
> 问题签名 02: 1.0.0.0
> 问题签名 03: d7f8a3c0
> 问题签名 04: PresentationFramework
> 问题签名 05: 4.8.3928.0
> 问题签名 06: 5d3907bb
> 问题签名 07: 2261
> 问题签名 08: f6
> 问题签名 09: System.Windows.Markup.XamlParse
> OS 版本: 6.1.7601.2.1.0.256.1
> 区域设置 ID: 2052
> 其他信息 1: 0a9e
> 其他信息 2: 0a9e372d3b4ad19135b953a78882e789
> 其他信息 3: 0a9e
> 其他信息 4: 0a9e372d3b4ad19135b953a78882e789

角度刁钻！专业测试吗？🙄🤔
