### ISSUE TITLE
windows 10 21H1 任务栏放在顶/底部，点击任意选项后没有任何反馈

### ISSUE THREAD

**Issue by myesn** [Uahh/ToastFish#27]
## 系统版本

![image](https://user-images.githubusercontent.com/18598579/129896564-9b09e6f9-f511-4479-878c-930c37703581.png)

## GIF 演示

![dashboard](https://user-images.githubusercontent.com/18598579/129897068-a5470e63-d3e4-4bf4-ade8-8b4c3893e51a.gif)

**Comment by Uahh** [comment]
请在系统设置里开启系统通知。

**Comment by Uahh** [comment]
> ## 系统版本
> ![image](https://user-images.githubusercontent.com/18598579/129896564-9b09e6f9-f511-4479-878c-930c37703581.png)
> 
> ## GIF 演示
> ![dashboard](https://user-images.githubusercontent.com/18598579/129897068-a5470e63-d3e4-4bf4-ade8-8b4c3893e51a.gif)

请在系统设置里开启系统通知。

**Comment by myesn** [comment]
谢谢
