### ISSUE TITLE
我錄製了介紹的YouTube影片...

### ISSUE THREAD

**Issue by emisjerry** [Uahh/ToastFish#28]
Hi,

我在YouTube上傳了一支ToastFish的介紹影片，希望作者可以撥冗指教。

用ToastFish「偷偷」學英、日文 🙈: https://youtu.be/LjTVvl0iwUI
Thanks.

**Comment by Uahh** [comment]
不好意思，週末玩的太開心了所以沒及時回复。感謝您的推廣，視頻做的很棒！ 我也會繼續做更新的。

祝工作順利
Thanks.

emisjerry ***@***.***>于2021年8月21日 周六21:17写道：
