### ISSUE TITLE
win11 无法启动报错

### ISSUE THREAD

**Issue by lhn2018** [Uahh/ToastFish#38]
win11系统下，双击exe程序直接报错

**Comment by Uahh** [comment]
我没有win11的环境，可以将报错信息贴出来吗？

**Comment by lhn2018** [comment]
之前就是 启动就退出 。。现在可以了。。。。




在 2021-12-28 09:43:44，"Uahh" ***@***.***> 写道：

我没有win11的环境，可以将报错信息贴出来吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
