### ISSUE TITLE
日语只有中级词吗0.0

### ISSUE THREAD

**Issue by QyoKLaku** [Uahh/ToastFish#39]
哈喽大佬你好，日语学习只有中级词和五十音吗，后续会不会添加初级词啊🤣🤣
有的话就更好了，谢谢大佬！

**Comment by Uahh** [comment]
> 哈喽大佬你好，日语学习只有中级词和五十音吗，后续会不会添加初级词啊🤣🤣 有的话就更好了，谢谢大佬！

已添加自定义词库功能
