### ISSUE TITLE
非常棒的一个软件，感谢！一些小小的建议~

### ISSUE THREAD

**Issue by BransonChen** [Uahh/ToastFish#40]
希望能够增加通知间隔的设置，设置每个单词弹窗的间隔，现在是点完一个立刻就出下一个了。
现在每天背完选定的单词后再开始就是新的单词了，能不能改成每日的方式，单天固定的单词来轮回学习，谢谢~~~

**Comment by Uahh** [comment]
已添加历史记录功能

> 希望能够增加通知间隔的设置，设置每个单词弹窗的间隔，现在是点完一个立刻就出下一个了。 现在每天背完选定的单词后再开始就是新的单词了，能不能改成每日的方式，单天固定的单词来轮回学习，谢谢~~~
