### ISSUE TITLE
每次重新打开exe.文件以后 前一天背过的单词清零

### ISSUE THREAD

**Issue by onesweetya** [Uahh/ToastFish#55]
exe.有桌面快捷方式吗？每次重新点开exe.文件以后前一天背过的单词都清零了是怎么回事呢

**Comment by FuckDoper** [comment]
lolllllllllllllllllllllllllllllllllllllll

**Comment by onesweetya** [comment]
您的邮件已收到，谢谢您！                            张天涯

**Comment by Uahh** [comment]
只用解压一次呀
