### ISSUE TITLE
过程中点其他的就会隐藏到通知栏

### ISSUE THREAD

**Issue by liurunhao** [Uahh/ToastFish#59]
在背的过程中比如回个消息点了其他地方，右下角通知就会隐藏到通知栏，点开通知栏才能看到，但那时候就是显示在右上方了，比较明显，想要重新显示在右下角只能再点开始，这样还是继续之前的顺序吗？测试的话，单词库是重新开始的还是加上之前背的？可以优化一下吗

**Comment by Uahh** [comment]
已增加记录功能，重新背可以直接导入历史记录。

> 在背的过程中比如回个消息点了其他地方，右下角通知就会隐藏到通知栏，点开通知栏才能看到，但那时候就是显示在右上方了，比较明显，想要重新显示在右下角只能再点开始，这样还是继续之前的顺序吗？测试的话，单词库是重新开始的还是加上之前背的？可以优化一下吗
