### ISSUE TITLE
window10系统，选择词汇 、设置单词个数以及 开始 后都没有弹出通知框

### ISSUE THREAD

**Issue by huajianyihujiu** [Uahh/ToastFish#6]

**Comment by huajianyihujiu** [comment]
由于没有任何通知栏弹出，所以整个软件都无法使用

**Comment by huajianyihujiu** [comment]
已经解决了：
![image](https://user-images.githubusercontent.com/48154006/120591223-5ebfb200-c46e-11eb-963f-4e6df2deb9bf.png)
打开应用通知开关即可。
软件很好用，另外，QQ群已满员，可否建个新群？

**Comment by Uahh** [comment]
升级群聊了，现在可以加！
