### ISSUE TITLE
win11无反应解决方法

### ISSUE THREAD

**Issue by talent0819** [Uahh/ToastFish#61]
在win11系统中，关闭专注助手即可弹出

**Comment by Ahashluxy** [comment]
亲测有用

**Comment by talent0819** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Uahh/ToastFish"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Uahh/ToastFish] win11无反应解决方法 (Issue #61)





 
亲测有用

**Comment by Proletain** [comment]
在设置中打开 系统>专注助手>优先级列表 后添加应用就可以了
