### ISSUE TITLE
win11自动关闭

### ISSUE THREAD

**Issue by ZhuQiuNianSan** [Uahh/ToastFish#65]
win11在单词经过一段时间约四五秒后就自动关闭了，有什么解决方法嘛

**Comment by Ahashluxy** [comment]
win11甚至打不开

**Comment by Uahh** [comment]
> win11在单词经过一段时间约四五秒后就自动关闭了，有什么解决方法嘛

在系统设置里可以设置通知停留时间，最高5分钟。

**Comment by Uahh** [comment]
> win11甚至打不开

打不开可以检查下系统设置是否开启了通知功能
